### ISSUE TITLE
doesn't work on macbook m4 with sequoia

### ISSUE THREAD

**Issue by guidovizioli** [julienXX/terminal-notifier#312]
Hi, I installed termina-notifier:

"terminal-notifier (2.0.0) is a command-line tool to send macOS User Notifications."

but nothing happens when i run commands like this:

"echo 'Piped Message Data!' | terminal-notifier -sound default"

My system is macbook pro M4 qith sequoia 15.3.1

Can you help me?

Thanks

Guido

**Comment by januszoles** [comment]
Mac Mini M4 15.3.2  (to make it works Allow Notifications MUST be ON)

System Settings... > Notifications > Applications Notifications > terminal-notifier > Allow Notifications > ON

![Image](https://github.com/user-attachments/assets/fcc36811-5fed-4645-b4bf-923cad438662)

**Comment by Taffer** [comment]
Same issue on my wife's M1 Air; all notifications settings are enabled, but running `terminal-notifier` displays nothing, and doesn't give an error. She's also on 15.3.2.

**Comment by fredb** [comment]
Might want to check if you don't have a Focus hiding them in Notification Center only.

**Comment by voidcoefficient** [comment]
Same on:

```
OS: macOS 15.3.2 24D81 arm64
Host: Mac14,2
Kernel: 24.3.0
CPU: Apple M2
```

✅ Not using "Do Not Disturb"
✅ Enabled application in notification settings
✅ Other notifications work as expected

**Comment by Taffer** [comment]
I was finally able to test this; in my case, the "Sleep" focus was still on. Turning it off let `terminal-notifier` display messages as I'd expect.

**Comment by DerZyklop** [comment]
With these settings, the notifications are still not showing up:

![Image](https://github.com/user-attachments/assets/866860f2-f74b-405c-8f25-4706ef3135d1)

![Image](https://github.com/user-attachments/assets/e4a30d13-0e4a-4760-967c-b2ad776899ef)

No 'Focus' is active.

![Image](https://github.com/user-attachments/assets/10b487fd-ecbb-48ff-977e-45907f5c4347)

System:

```
OS: macOS 15.0.1 24A348 arm64 
Host: MacBookPro18,1 
Kernel: 24.0.0 
Shell: bash 3.2.57 
CPU: Apple M1 Pro 
```

**Comment by JaysonAlbert** [comment]
I'm using macOs 15.5  ,this is how i manage to get it work @DerZyklop  @voidcoefficient @Taffer


1. clone the code, and open it using Xcode
2. increase the minimum deployment target

![Image](https://github.com/user-attachments/assets/a7ea8d9c-97cc-43fe-ad9e-39d70185e731)
3. build the project `xcodebuild -project "Terminal Notifier.xcodeproj"`
4. copy to Applications folder: `cp -R build/Release/terminal-notifier.app /Applications/`
5. create a file  `/usr/local/bin/terminal-notifier` contains:
```
#!/bin/bash
exec "/Applications/terminal-notifier.app/Contents/MacOS/terminal-notifier" "$@"
```

**Comment by saidelike** [comment]
> I'm using macOs 15.5 ,this is how i manage to get it work [@DerZyklop](https://github.com/DerZyklop) [@voidcoefficient](https://github.com/voidcoefficient) [@Taffer](https://github.com/Taffer)
> 
>     1. clone the code, and open it using Xcode
> 
>     2. increase the minimum deployment target
> 
> 
> ![Image](https://github.com/user-attachments/assets/a7ea8d9c-97cc-43fe-ad9e-39d70185e731) 3. build the project `xcodebuild -project "Terminal Notifier.xcodeproj"` 4. copy to Applications folder: `cp -R build/Release/terminal-notifier.app /Applications/` 5. create a file `/usr/local/bin/terminal-notifier` contains:
> 
> ```
> #!/bin/bash
> exec "/Applications/terminal-notifier.app/Contents/MacOS/terminal-notifier" "$@"
> ```

I've done that with `MACOSX_DEPLOYMENT_TARGET = 26.2` and can confirm it works as expected. Just make sure to change the permissions for `/usr/local/bin/terminal-notifier` to be executable.

```
sudo chmod +x /usr/local/bin/terminal-notifier
```

**Comment by pjurkowski** [comment]
I had similar issues and found out that sending any notifications without
`-sender $sender`  
does not work so first post example 
`echo 'Piped Message Data!' | terminal-notifier -sound default`  
will work and play sound if it will be executed with  
`echo 'Piped Message Data!' | terminal-notifier -sound default -sender me`

I'm running mac os Tahoe 26.4.1

**Comment by julienXX** [comment]
Fixed in version 3.0.0. Feel free to re-open if needed.

**Comment by koichirose** [comment]
Hi, I'm still having issues after the update, not receiving any notifications.
```
$ terminal-notifier -diagnose                                                                                                                                                                                                                                

terminal-notifier 3.0.0
  bundle id           fr.julienxx.oss.terminal-notifier
  bundle path         /opt/homebrew/Cellar/terminal-notifier/3.0.0_1/terminal-notifier.app
  macOS               Version 26.5 (Build 25F71)
  NotificationCenter  running

  authorization       authorized
  alerts              enabled
  alert style         banners
  sounds              enabled
  notification centre enabled
  lock screen         enabled
  previews            when unlocked
  critical alerts     not supported
  time sensitive      not supported
  scheduled delivery  not supported

No problems found.

```

I verified that notifications are enabled via system settings as well.
`terminal-notifier -message "test"` doesn't show anything.

I also uninstalled/reinstalled (via brew).
If it helps, the command `tccutil reset UserNotification fr.julienxx.oss.terminal-notifier` says:
`tccutil: Failed to reset UserNotification approval status for fr.julienxx.oss.terminal-notifier`

**Comment by koichirose** [comment]
Nevermind, 3.1.0 seems to have fixed it for me.
